# Generated by Django 2.0.4 on 2018-04-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='to_use',
            new_name='to_user',
        ),
    ]
