# Generated by Django 2.0.4 on 2018-04-30 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_auto_20180427_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='game',
            field=models.ForeignKey(default=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='gameplay.Game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='move',
            name='by_first_player',
            field=models.BooleanField(editable=False),
        ),
    ]
